// <auto-generated />
using CompanyInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyInfo.API.Migrations
{
    [DbContext(typeof(CompanyInfoDbContext))]
    [Migration("20230930062537_SeedDataAdded")]
    partial class SeedDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("CompanyInfo.API.Entities.CarModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyID = 1,
                            Description = "This is Elantra",
                            Model = "Elantra"
                        },
                        new
                        {
                            ID = 2,
                            CompanyID = 1,
                            Description = "This is Kona",
                            Model = "Kona"
                        },
                        new
                        {
                            ID = 3,
                            CompanyID = 2,
                            Description = "This is A30",
                            Model = "A30"
                        },
                        new
                        {
                            ID = 4,
                            CompanyID = 2,
                            Description = "This is Heyue RS",
                            Model = "Heyue RS"
                        },
                        new
                        {
                            ID = 5,
                            CompanyID = 3,
                            Description = "This is XC90",
                            Model = "XC90"
                        },
                        new
                        {
                            ID = 6,
                            CompanyID = 3,
                            Description = "This is V60",
                            Model = "V60"
                        });
                });

            modelBuilder.Entity("CompanyInfo.API.Entities.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "This is Hyundai",
                            Name = "Hyundai"
                        },
                        new
                        {
                            ID = 2,
                            Description = "This is Jac",
                            Name = "Jac"
                        },
                        new
                        {
                            ID = 3,
                            Description = "This is Volvo",
                            Name = "Volvo"
                        });
                });

            modelBuilder.Entity("CompanyInfo.API.Entities.CarModel", b =>
                {
                    b.HasOne("CompanyInfo.API.Entities.Company", "Company")
                        .WithMany("CarModels")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyInfo.API.Entities.Company", b =>
                {
                    b.Navigation("CarModels");
                });
#pragma warning restore 612, 618
        }
    }
}
